package com.example.flower_show.data.repository

import com.example.flower_show.model.*

internal object FallbackData {

    private val U = ""

    // [AI-assisted] Recommend words generated by Claude based on each video's title + tags
    // AI 辅助：Claude 根据视频标题+标签生成的推荐搜索词
    fun createVideos() = listOf(
        VideoItem("v001","梅西生涯十佳进球集锦","足球天下","https://picsum.photos/200/200?random=1",
            "https://media.w3.org/2010/05/sintel/trailer.mp4",
            likes=125000,comments=8900,collections=3400,shares=12000,
            tags=listOf("足球","梅西","进球","巴萨","西甲"),
            recommendWords=listOf("梅西生涯进球","巴萨经典比赛","足球精彩瞬间","西甲进球集锦","梅西世界杯","欧冠决赛回放","任意球教学","C罗对比","阿根廷国家队长","足球技巧"),
            qualityUrls=mapOf("720p" to "https://media.w3.org/2010/05/sintel/trailer.mp4")),
        VideoItem("v002","iPhone 16 Pro Max 深度评测","科技评测室","https://picsum.photos/200/200?random=2",
            "https://media.w3.org/2010/05/bunny/trailer.mp4",
            likes=78000,comments=5400,collections=1800,shares=9600,
            tags=listOf("手机","iPhone","评测","苹果","科技"),
            recommendWords=listOf("iPhone16评测","苹果新机发布","手机推荐2024","华为对比苹果","手机拍照评测","性价比手机","5G手机推荐","苹果发布会","数码开箱","手机续航测试"),
            qualityUrls=mapOf("720p" to "https://media.w3.org/2010/05/bunny/trailer.mp4")),
        VideoItem("v003","四川麻辣火锅正宗做法","美食工坊","https://picsum.photos/200/200?random=3",
            "https://media.w3.org/2010/05/video/movie_300.mp4",
            likes=67000,comments=4500,collections=3200,shares=15000,
            tags=listOf("美食","火锅","四川","麻辣","烹饪"),
            recommendWords=listOf("火锅做法大全","四川美食推荐","麻辣火锅底料","家常菜谱教程","重庆火锅探店","串串香做法","川菜教学","冬季暖身食谱","美食博主推荐","火锅蘸料配方")),
        VideoItem("v004","云南大理丽江自由行深度攻略","旅行日记","https://picsum.photos/200/200?random=4",
            "https://media.w3.org/2010/05/bunny/movie.mp4",
            likes=112000,comments=7800,collections=6700,shares=23000,
            tags=listOf("旅游","云南","大理","丽江","自由行"),
            recommendWords=listOf("云南旅游攻略2024","大理丽江自由行","国内旅行推荐","自驾游路线","洱海拍照打卡","玉龙雪山攻略","民宿推荐","穷游攻略","香格里拉旅游","西双版纳景点")),
        VideoItem("v005","周杰伦经典歌曲钢琴演奏合集","音乐时光","https://picsum.photos/200/200?random=5",
            "https://media.w3.org/2010/05/sintel/trailer.mp4",
            likes=234000,comments=18000,collections=12000,shares=45000,
            tags=listOf("音乐","周杰伦","钢琴","流行","华语"),
            recommendWords=listOf("周杰伦歌曲合集","钢琴演奏教学","华语经典歌曲","流行音乐推荐","零基础学钢琴","晴天钢琴谱","林俊杰对比","演唱会现场","抖音热门BGM","治愈系音乐")),
        VideoItem("v006","王者荣耀S35赛季上分英雄推荐","电竞玩家","https://picsum.photos/200/200?random=1",
            "https://media.w3.org/2010/05/bunny/trailer.mp4",
            likes=267000,comments=21000,collections=9800,shares=45000,
            tags=listOf("游戏","王者荣耀","电竞","手游"),
            recommendWords=listOf("王者荣耀最新赛季","S35上分英雄","手游推荐排行榜","英雄联盟手游","电竞比赛直播","王者教学视频","打野思路教学","国服最强李白","游戏实况解说","原神对比")),
        VideoItem("v007","10分钟高效腹肌训练跟练","健身达人","https://picsum.photos/200/200?random=2",
            "https://media.w3.org/2010/05/video/movie_300.mp4",
            likes=145000,comments=9800,collections=7800,shares=28000,
            tags=listOf("健身","腹肌","训练","运动"),
            recommendWords=listOf("腹肌训练教程","家庭健身计划","减肥运动推荐","马甲线速成","HIIT燃脂","瑜伽入门教学","增肌食谱","健身博主推荐","拉伸动作教学","跳绳减肥效果")),
        VideoItem("v008","搞笑猫咪犯错合集2024","萌宠日记","https://picsum.photos/200/200?random=3",
            "https://media.w3.org/2010/05/sintel/trailer.mp4",
            likes=345000,comments=28000,collections=18000,shares=78000,
            tags=listOf("猫咪","宠物","搞笑","萌宠"),
            recommendWords=listOf("猫咪搞笑合集","萌宠视频","喵星人日常","狗狗训练教程","宠物用品推荐","布偶猫价格","流浪猫救助","仓鼠可爱视频","哈士奇拆家","猫粮测评")),
        VideoItem("v009","2024年度最佳国产电影推荐","影视推荐","https://picsum.photos/200/200?random=4",
            "https://media.w3.org/2010/05/bunny/trailer.mp4",
            likes=89000,comments=6700,collections=3400,shares=15000,
            tags=listOf("电影","国产","推荐","院线"),
            recommendWords=listOf("2024电影推荐","豆瓣高分电影","国产电影排行榜","院线新片速递","悬疑片推荐","科幻电影合集","搞笑喜剧电影","Netflix推荐","电影解说速看","好莱坞大片")),
    )

    fun createImageCards() = listOf(
        ImageCardItem("img001","搞笑猫咪表情包合集","萌宠日记","https://picsum.photos/720/900?random=30",89000,12000),
        ImageCardItem("img002","自然风光摄影精选","环球旅行家","https://picsum.photos/720/1280?random=31",67000,4500),
        ImageCardItem("img003","甜品美食摄影","美食工坊","https://picsum.photos/720/900?random=32",45000,3200),
        ImageCardItem("img004","科技数码开箱图赏","科技评测室","https://picsum.photos/720/1280?random=33",34000,2100),
        ImageCardItem("img005","秋日穿搭指南","时尚圈","https://picsum.photos/720/900?random=34",56000,4300),
    )

    fun createAlbums() = listOf(
        AlbumCardItem("alb001","搞笑猫咪表情包合集","萌宠日记","https://picsum.photos/200/200?random=3",
            slides=listOf(AlbumSlide(0,"https://picsum.photos/720/1280?random=40"),AlbumSlide(0,"https://picsum.photos/720/1280?random=41"),AlbumSlide(0,"https://picsum.photos/720/1280?random=42"),AlbumSlide(0,"https://picsum.photos/720/1280?random=43")),
            likes=345000,comments=28000,shares=78000,
            tags=listOf("猫咪","宠物","搞笑","萌宠"),recommendWords=listOf("猫咪搞笑合集","萌宠表情包","喵星人日常")),
        AlbumCardItem("alb002","自然风光摄影精选","环球旅行家","https://picsum.photos/200/200?random=4",
            slides=listOf(AlbumSlide(0,"https://picsum.photos/720/1280?random=50"),AlbumSlide(0,"https://picsum.photos/720/1280?random=51"),AlbumSlide(0,"https://picsum.photos/720/1280?random=52")),
            likes=67000,comments=4500,shares=12000,
            tags=listOf("自然","风光","摄影","美景"),recommendWords=listOf("自然风光","摄影精选","美景壁纸")),
        AlbumCardItem("alb003","科技数码开箱图赏","科技评测室","https://picsum.photos/200/200?random=1",
            slides=listOf(AlbumSlide(0,"https://picsum.photos/720/1280?random=60"),AlbumSlide(0,"https://picsum.photos/720/1280?random=61"),AlbumSlide(0,"https://picsum.photos/720/1280?random=62"),AlbumSlide(0,"https://picsum.photos/720/1280?random=63"),AlbumSlide(0,"https://picsum.photos/720/1280?random=64")),
            likes=34000,comments=2100,shares=8900,
            tags=listOf("科技","数码","开箱","评测"),recommendWords=listOf("数码开箱","科技产品","新机图赏")),
    )
}
